name: ci

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - name: Windows x86_64
            os: windows-2022
          # MacOS
          - name: MacOS 14
            os: macos-14
          - name: MacOS 13 x86_64
            os: macos-13
          # Linux
          - name: Linux x86_64
            os: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests with all features
      run: cargo test --verbose --all-features
    - name: Test unrar_sys library
      run: cargo test --verbose --package=unrar_sys
